server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          #uri: https://git.oschina.net/itmuch/spring-cloud-config-repo      # 配置Git仓库的地址
          uri:  https://gitee.com/haowei0315/spring-cloud-config-repo      # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
  rabbitmq:
    host: 192.168.98.130
    port: 5672
    username: root
    password: root
    virtual-host: adminV

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
